const cyrillicMap: Record<string, string> = {
  А: 'A',
  а: 'a',
  Б: 'B',
  б: 'b',
  В: 'V',
  в: 'v',
  Г: 'G',
  г: 'g',
  Д: 'D',
  д: 'd',
  Е: 'E',
  е: 'e',
  Ё: 'Yo',
  ё: 'yo',
  Ж: 'J',
  ж: 'j',
  З: 'Z',
  з: 'z',
  И: 'I',
  и: 'i',
  Й: 'Y',
  й: 'y',
  К: 'K',
  к: 'k',
  Л: 'L',
  л: 'l',
  М: 'M',
  м: 'm',
  Н: 'N',
  н: 'n',
  О: 'O',
  о: 'o',
  П: 'P',
  п: 'p',
  Р: 'R',
  р: 'r',
  С: 'S',
  с: 's',
  Т: 'T',
  т: 't',
  У: 'U',
  у: 'u',
  Ф: 'F',
  ф: 'f',
  Х: 'X',
  х: 'x',
  Ц: 'S',
  ц: 's',
  Ч: 'Ch',
  ч: 'ch',
  Ш: 'Sh',
  ш: 'sh',
  Ъ: "'",
  ъ: "'",
  Ь: '',
  ь: '',
  Э: 'E',
  э: 'e',
  Ю: 'Yu',
  ю: 'yu',
  Я: 'Ya',
  я: 'ya',
  Ў: "O'",
  ў: "o'",
  Қ: 'Q',
  қ: 'q',
  Ғ: "G'",
  ғ: "g'",
  Ҳ: 'H',
  ҳ: 'h',
};

export const cyrillicToLatinText = (text: string): string =>
  text.replace(/[А-Яа-яЁёЎўҚқҒғҲҳЪъЬь]/g, (char) => cyrillicMap[char] ?? char);

export const latinizeQuestionPayload = <T extends {
  prompt?: string;
  options?: Array<{ optionText?: string; matchText?: string }>;
}>(
  payload: T,
): T => ({
  ...payload,
  prompt: payload.prompt ? cyrillicToLatinText(payload.prompt) : payload.prompt,
  options: payload.options?.map((option) => ({
    ...option,
    optionText: option.optionText ? cyrillicToLatinText(option.optionText) : option.optionText,
    matchText: option.matchText ? cyrillicToLatinText(option.matchText) : option.matchText,
  })),
});
